FROM nodeschool/base

RUN npm install browserify-adventure -g
RUN npm install stream-combiner2 browserify@4.x.x through2 uniq brfs browserify-shim concat-stream split quote-stream
RUN rm -rf ./node_modules
